# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "blogs", :force => true do |t|
  end

  create_table "diaries", :force => true do |t|
  end

  create_table "friends", :force => true do |t|
  end

  create_table "group_messages", :force => true do |t|
  end

  create_table "groupmessages", :force => true do |t|
  end

  create_table "groups", :force => true do |t|
  end

  create_table "groups_users", :force => true do |t|
  end

  create_table "messages", :force => true do |t|
  end

  create_table "photos", :force => true do |t|
  end

  create_table "posts", :force => true do |t|
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "squareclasses", :force => true do |t|
  end

  create_table "user_details", :force => true do |t|
  end

  create_table "user_friends", :force => true do |t|
  end

  create_table "users", :force => true do |t|
  end

  create_table "users_users", :force => true do |t|
  end

end
